services:
  app:
    build: .
    volumes:
      - .:/app       # Mount the whole project root
    ports:
      - "8000:8000"
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --reload