"""create thoughts table 2

Revision ID: 103a9c0b83a0
Revises: 2eb7fbede9d7
Create Date: 2026-03-15 07:19:27.505848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103a9c0b83a0'
down_revision: Union[str, Sequence[str], None] = '2eb7fbede9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
