"""added title in thought model

Revision ID: 25817a9f00b5
Revises: 227b03ffb3b0
Create Date: 2026-03-15 07:41:48.551130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25817a9f00b5'
down_revision: Union[str, Sequence[str], None] = '227b03ffb3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thoughts_id'), table_name='thoughts')
    op.drop_table('thoughts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thoughts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('thoughts_pkey'))
    )
    op.create_index(op.f('ix_thoughts_id'), 'thoughts', ['id'], unique=False)
    # ### end Alembic commands ###
