"""create thoughts table

Revision ID: 2eb7fbede9d7
Revises: 
Create Date: 2026-03-15 06:44:13.287270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb7fbede9d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Thoughts_id'), table_name='Thoughts')
    op.drop_table('Thoughts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Thoughts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Thoughts_pkey'))
    )
    op.create_index(op.f('ix_Thoughts_id'), 'Thoughts', ['id'], unique=False)
    # ### end Alembic commands ###
