"""Added nullable=False

Revision ID: 87878003953d
Revises: 25817a9f00b5
Create Date: 2026-03-15 07:53:42.310468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87878003953d'
down_revision: Union[str, Sequence[str], None] = '25817a9f00b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thoughts_id'), table_name='thoughts')
    op.drop_index(op.f('ix_thoughts_title'), table_name='thoughts')
    op.drop_table('thoughts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thoughts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('thoughts_pkey'))
    )
    op.create_index(op.f('ix_thoughts_title'), 'thoughts', ['title'], unique=False)
    op.create_index(op.f('ix_thoughts_id'), 'thoughts', ['id'], unique=False)
    # ### end Alembic commands ###
