"""make_uuid_not_null

Revision ID: 084e5dd377ed
Revises: 7e233c4d6804
Create Date: 2026-08-09 08:57:18.360743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084e5dd377ed'
down_revision: Union[str, Sequence[str], None] = '7e233c4d6804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('field_values', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('journal_sections', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('journals', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('section_fields', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('section_templates', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('thoughts', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('thoughts', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('section_templates', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('section_fields', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('journals', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('journal_sections', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('field_values', 'uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
