"""add_last_reminder_sent_at_to_tasks

Revision ID: 25f3e3dad6d9
Revises: d7369bee68ff
Create Date: 2026-08-10 18:52:02.362648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f3e3dad6d9'
down_revision: Union[str, Sequence[str], None] = 'd7369bee68ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_reminder_sent_at')
    # ### end Alembic commands ###
