"""Add recurrence_interval to tasks

Revision ID: 3b78baa0b30e
Revises: 084e5dd377ed
Create Date: 2026-08-09 10:02:01.644343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b78baa0b30e'
down_revision: Union[str, Sequence[str], None] = '084e5dd377ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_interval', sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', name='taskrecurrence'), server_default='NONE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_interval')
    # ### end Alembic commands ###
