"""Added pin and start feature in thoughts

Revision ID: 51dc5cc86f87
Revises: 25f3e3dad6d9
Create Date: 2026-08-14 13:59:24.263154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dc5cc86f87'
down_revision: Union[str, Sequence[str], None] = '25f3e3dad6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoughts', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('thoughts', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('thoughts', sa.Column('pinned_order', sa.Integer(), nullable=True))
    op.add_column('thoughts', sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thoughts', 'is_starred')
    op.drop_column('thoughts', 'pinned_order')
    op.drop_column('thoughts', 'pinned_at')
    op.drop_column('thoughts', 'is_pinned')
    # ### end Alembic commands ###
