"""Add fields in notebook

Revision ID: 5aa4f50681e1
Revises: 08b92724a867
Create Date: 2026-09-15 16:14:55.096146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa4f50681e1'
down_revision: Union[str, Sequence[str], None] = '08b92724a867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notes', sa.Column('is_starred', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_starred')
    op.drop_column('notes', 'is_pinned')
    # ### end Alembic commands ###
