"""add_uuid_fields

Revision ID: 7e233c4d6804
Revises: e7c8503f038c
Create Date: 2026-08-09 08:53:43.462584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e233c4d6804'
down_revision: Union[str, Sequence[str], None] = 'e7c8503f038c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_values', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_field_values_uuid'), 'field_values', ['uuid'], unique=True)
    op.add_column('journal_sections', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_journal_sections_uuid'), 'journal_sections', ['uuid'], unique=True)
    op.add_column('journals', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_journals_uuid'), 'journals', ['uuid'], unique=True)
    op.add_column('section_fields', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_section_fields_uuid'), 'section_fields', ['uuid'], unique=True)
    op.add_column('section_templates', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_section_templates_uuid'), 'section_templates', ['uuid'], unique=True)
    op.add_column('tasks', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tasks_uuid'), 'tasks', ['uuid'], unique=True)
    op.add_column('thoughts', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_thoughts_uuid'), 'thoughts', ['uuid'], unique=True)
    op.add_column('users', sa.Column('uuid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_column('users', 'uuid')
    op.drop_index(op.f('ix_thoughts_uuid'), table_name='thoughts')
    op.drop_column('thoughts', 'uuid')
    op.drop_index(op.f('ix_tasks_uuid'), table_name='tasks')
    op.drop_column('tasks', 'uuid')
    op.drop_index(op.f('ix_section_templates_uuid'), table_name='section_templates')
    op.drop_column('section_templates', 'uuid')
    op.drop_index(op.f('ix_section_fields_uuid'), table_name='section_fields')
    op.drop_column('section_fields', 'uuid')
    op.drop_index(op.f('ix_journals_uuid'), table_name='journals')
    op.drop_column('journals', 'uuid')
    op.drop_index(op.f('ix_journal_sections_uuid'), table_name='journal_sections')
    op.drop_column('journal_sections', 'uuid')
    op.drop_index(op.f('ix_field_values_uuid'), table_name='field_values')
    op.drop_column('field_values', 'uuid')
    # ### end Alembic commands ###
