"""add_reminder_settings

Revision ID: 7f56de753ad3
Revises: 9dde3fa15d29
Create Date: 2026-07-21 18:45:46.614045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f56de753ad3'
down_revision: Union[str, Sequence[str], None] = '9dde3fa15d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(), server_default='Asia/Kolkata', nullable=False))
    op.add_column('users', sa.Column('journal_reminder_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('journal_reminder_time', sa.String(), server_default='22:00:00', nullable=False))
    op.add_column('users', sa.Column('last_journal_reminder_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_journal_reminder_date')
    op.drop_column('users', 'journal_reminder_time')
    op.drop_column('users', 'journal_reminder_active')
    op.drop_column('users', 'timezone')
    op.drop_column('tasks', 'reminder_sent')
    # ### end Alembic commands ###
