"""add_order_to_field_values

Revision ID: b0f1092c5b92
Revises: 51dc5cc86f87
Create Date: 2026-08-14 14:23:50.810735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f1092c5b92'
down_revision: Union[str, Sequence[str], None] = '51dc5cc86f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_values', sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_values', 'order')
    # ### end Alembic commands ###
