"""changed the time

Revision ID: e7c8503f038c
Revises: 7f56de753ad3
Create Date: 2026-07-22 18:39:48.099159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c8503f038c'
down_revision: Union[str, Sequence[str], None] = '7f56de753ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'journal_reminder_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=False,
               existing_server_default=sa.text("'22:00:00'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'journal_reminder_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'22:00:00'::character varying"))
    # ### end Alembic commands ###
