"""add fk indexes

Revision ID: f69e703898aa
Revises: 3c60e5befc3b
Create Date: 2026-03-21 18:18:53.697520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69e703898aa'
down_revision: Union[str, Sequence[str], None] = '3c60e5befc3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_field_values_field_id'), 'field_values', ['field_id'], unique=False)
    op.create_index(op.f('ix_field_values_section_id'), 'field_values', ['section_id'], unique=False)
    op.create_index(op.f('ix_journal_sections_journal_id'), 'journal_sections', ['journal_id'], unique=False)
    op.create_index(op.f('ix_journal_sections_template_id'), 'journal_sections', ['template_id'], unique=False)
    op.create_index(op.f('ix_journals_user_id'), 'journals', ['user_id'], unique=False)
    op.create_index(op.f('ix_section_fields_template_id'), 'section_fields', ['template_id'], unique=False)
    op.create_index(op.f('ix_section_templates_user_id'), 'section_templates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_section_templates_user_id'), table_name='section_templates')
    op.drop_index(op.f('ix_section_fields_template_id'), table_name='section_fields')
    op.drop_index(op.f('ix_journals_user_id'), table_name='journals')
    op.drop_index(op.f('ix_journal_sections_template_id'), table_name='journal_sections')
    op.drop_index(op.f('ix_journal_sections_journal_id'), table_name='journal_sections')
    op.drop_index(op.f('ix_field_values_section_id'), table_name='field_values')
    op.drop_index(op.f('ix_field_values_field_id'), table_name='field_values')
    # ### end Alembic commands ###
