"""Add OTP fields

Revision ID: fa24b163ef6c
Revises: f69e703898aa
Create Date: 2026-03-29 18:04:37.161324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa24b163ef6c'
down_revision: Union[str, Sequence[str], None] = 'f69e703898aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_layout_template_rows_layout_template_id'), table_name='journal_layout_template_rows')
    op.drop_index(op.f('ix_journal_layout_template_rows_section_template_id'), table_name='journal_layout_template_rows')
    op.drop_table('journal_layout_template_rows')
    op.drop_index(op.f('ix_journal_layout_template_sections_journal_layout_template_id'), table_name='journal_layout_template_sections')
    op.drop_index(op.f('ix_journal_layout_template_sections_section_template_id'), table_name='journal_layout_template_sections')
    op.drop_table('journal_layout_template_sections')
    op.drop_index(op.f('ix_journal_layout_templates_user_id'), table_name='journal_layout_templates')
    op.drop_table('journal_layout_templates')
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp_code')
    op.create_table('journal_layout_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'TERMINATED', name='template_status'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('journal_layout_templates_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_layout_templates_pkey'))
    )
    op.create_index(op.f('ix_journal_layout_templates_user_id'), 'journal_layout_templates', ['user_id'], unique=False)
    op.create_table('journal_layout_template_sections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('journal_layout_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal_layout_template_id'], ['journal_layout_templates.id'], name=op.f('journal_layout_template_section_journal_layout_template_id_fkey')),
    sa.ForeignKeyConstraint(['section_template_id'], ['section_templates.id'], name=op.f('journal_layout_template_sections_section_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_layout_template_sections_pkey'))
    )
    op.create_index(op.f('ix_journal_layout_template_sections_section_template_id'), 'journal_layout_template_sections', ['section_template_id'], unique=False)
    op.create_index(op.f('ix_journal_layout_template_sections_journal_layout_template_id'), 'journal_layout_template_sections', ['journal_layout_template_id'], unique=False)
    op.create_table('journal_layout_template_rows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('layout_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['layout_template_id'], ['journal_layout_templates.id'], name=op.f('journal_layout_template_rows_layout_template_id_fkey')),
    sa.ForeignKeyConstraint(['section_template_id'], ['section_templates.id'], name=op.f('journal_layout_template_rows_section_template_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('journal_layout_template_rows_pkey'))
    )
    op.create_index(op.f('ix_journal_layout_template_rows_section_template_id'), 'journal_layout_template_rows', ['section_template_id'], unique=False)
    op.create_index(op.f('ix_journal_layout_template_rows_layout_template_id'), 'journal_layout_template_rows', ['layout_template_id'], unique=False)
    # ### end Alembic commands ###
